FILENAME_SCREEN equ 'Screen.bmp'
FILENAME_PLAY equ 'Play.bmp'
FILENAME_LB equ 'lb.bmp'
FILENAME_INST equ 'Inst.bmp'
FILENAME_NA equ 'NA.bmp'
FILENAME_INST_1 equ '1.bmp'
FILENAME_INST_2 equ '2.bmp'
FILENAME_INST_3 equ '3.bmp'
FILENAME_INST_4 equ '4.bmp'

FILE_ROWS = 200
FILE_COLS = 320

;Play Banner values
PLAY_RIGHT_COL = 187
PLAY_LEFT_COL = 137
PLAY_TOP_ROW = 50
PLAY_BOTTOM_ROW = 71

;Leaderboard Banner values
LB_RIGHT_COL = 239
LB_LEFT_COL = 92
LB_TOP_ROW = 78
LB_BOTTOM_ROW = 89

;Game instructions Banner values
INST_RIGHT_COL = 270
INST_LEFT_COL = 51
INST_TOP_ROW = 96
INST_BOTTOM_ROW = 107

;Quit Banner values
QUIT_RIGHT_COL_OPEN = 34
QUIT_LEFT_COL_OPEN = 10
QUIT_TOP_ROW_OPEN = 6
QUIT_BOTTOM_ROW_OPEN = 31

;Arrow forward game manual
ARROW_FORWARD_RIGHT_COL = 195
ARROW_FORWARD_LEFT_COL = 177
ARROW_FORWARD_TOP_ROW = 183
ARROW_FORWARD_BOTTOM_ROW = 198

;Arrow backward  game manual
ARROW_BACKWARD_RIGHT_COL = 160
ARROW_BACKWARD_LEFT_COL = 144
ARROW_BACKWARD_TOP_ROW = 183
ARROW_BACKWARD_BOTTOM_ROW = 193
